### ISSUE TITLE
option for default hex number parsing

### ISSUE THREAD

**Issue by mrexodia** [keystone-engine/keystone#11]
It would be great if there was an option/syntax to override number parsing. With this option all numbers are interpreted as hex (`mov eax, 01334000` assembles to `mov eax, 0x1334000` instead of `mov eax, 0x5B800`).

**Comment by mrexodia** [comment]
Multiple people have requested this option in the x64dbg issue tracker now.

**Comment by aquynh** [comment]
is it possible for x64dbg to stick `0x` in front of every immediate, before feeding assembly code to Keystone?

**Comment by mrexodia** [comment]
Yes, but that would require x64dbg to parse assembly, which is undesired.

**Comment by aquynh** [comment]
will see when i can do this.

**Comment by aquynh** [comment]
what can be the name of this option, in the form of KS_OPT_SYNTAX_xxx?

**Comment by mrexodia** [comment]
It could be a directive in the assembler like suggested, or a random option
name. Maybe_RADIX16

**Comment by aquynh** [comment]
what does RADIX stand for?

**Comment by mrexodia** [comment]
Just the number base.

**Comment by aquynh** [comment]
Ok, KS_OPT_SYNTAX_RADIX16 is a good name.

**Comment by aquynh** [comment]
done, see https://github.com/keystone-engine/keystone/commit/eac9cc9d6712c4417ce57cb0aedeb8f0a39667c5 (including some samples on `KS_OPT_SYNTAX_RADIX16`  in `samples/sample.c`)

**Comment by mrexodia** [comment]
Okay, I will test it as soon as possible!

**Comment by aquynh** [comment]
do you have any issues with this new option?

**Comment by mrexodia** [comment]
No, I have been very busy with University. It's still on my backlog.

**Comment by mrexodia** [comment]
Okay, so I tested and it does work for decimal constants `mov eax,123` assembles to `mov eax,0x123` but you can still not use hexadecimal values in the constant, so `mov eax,abc` fails with error 144.

**Comment by aquynh** [comment]
Because in this case Keystone does not know abc is label, or constant.

**Comment by mrexodia** [comment]
Well then what is the point of a radix16 option jf you cannot enter hex
numbers?

**Comment by aquynh** [comment]
This case is ambigous: how do you know abc is label, or number??

**Comment by mrexodia** [comment]
I don't know how keystone handles this but the radix16 option has to be requested so it's safe to assume that it's not a label. In x64dbg hex number have priority over labels, so a label `beef` will resolve to `0xBEEF` and not the label address because that's the desired behavior.

**Comment by aquynh** [comment]
How other assemblers (nasm?) handle this case?

**Comment by aquynh** [comment]
How masm & gas handle this case with radix16 directive?

**Comment by mrexodia** [comment]
MASM requires a `0` in front of the number. I disagree with this though, my suggestion is to assume it is a number if it is a number or if that's too edgy, check if it's a label and change it to a number if assembling with that fails.

**Comment by aquynh** [comment]
Masm does it right: you must avoid ambiguous, dont confuse your users. So i would suggest you take the same approach for x64dbg

**Comment by mrexodia** [comment]
I disagree, zero prefixed numbers are also used for octal. If you don't
want to implement it, feel free to close the issue, but there is absolutely
no ambiguity here there are no labels present in single instruction
assembling.

**Comment by aquynh** [comment]
Think about that: if in your code has a label "abc", then this instruction confuses your own user, no?

**Comment by mrexodia** [comment]
External labels are not supported by keystone anyway right? And no it
doesn't confuse users it has been the default behavior for three years.

**Comment by aquynh** [comment]
symbols will be supported with a new API, but that is another story. 

in case the code has both label "abc" & "mov eax, abc", how do they know what this instruction mean?

**Comment by mrexodia** [comment]
They don't, but since you explicitly choose for hexadecimal numbers you can
safely assume that the user wants 0xabc when seeing "abc"

**Comment by aquynh** [comment]
but the assumption can be wrong. so in this case, user must look at the
opcode to figure out what the instruction really does??

**Comment by mrexodia** [comment]
You make an OPTION to change the default assumption. That's the whole point
of the option, if you document the assumption it is the desired behavior.

**Comment by aquynh** [comment]
if the document of x64dbg is like "by choosing this radix16 option, you accept that you may be confused with some output, and in that case you have to look at the opcode to clear your doubts", then i agree that is fine. 

it is your choice, but personally, i would do my best to never confuse users.

**Comment by mrexodia** [comment]
No you don't confuse users by clearly documenting what an option does. The
option I requested was to support radix16 numbers like "abc" plain in the
assembler input. It's not ambiguous if the choice is clear beforehand. Now
as developer you can also simply throw an error "ambiguous input" if "abc"
resolves to two possible values if you want to avoid possible user
confusion in case they didn't check the documentation of the option they
just manually enabled.

As a train of thought, what about the label "eax"? Isn't that just as
ambiguous?

**Comment by blaquee** [comment]
This option would make sense as long as it is just that. An explicit OPTION. If a user decides to use it they should be aware of what they are enabling. If popular assemblers support radix16 input, then it would make sense that keystone (an assembler of sorts) would also support this kind of input.

**Comment by techbliss** [comment]
Sorry for bumping into the issue , but i can't either see the downside of having a OPTION to support radix 16. If the little workaround when resolving to two values, throwing a error sounds reasonable.

**Comment by Chandlr** [comment]
Iam all for the support of radix16 and i agree with techbliss and blaquee and mrexodia

**Comment by aquynh** [comment]
this is not related, but you might be interested: Keystone now supports symbol resolving to handle missing symbols at run-time. see https://github.com/keystone-engine/keystone/issues/244, and report if you find any issues.

**Comment by JackieSpring** [comment]
i have some issues with gas syntax and the _RADIX16, in fact I cannot turn it off, when i try to assemble this line:
    movq $12, %rax
it gets assembled as:
    movq $0x12, %rax
and so is for memory like
    movl 12(%esp), %ecx
that become:
    movl 0x12(%esp), %ecx
what's even worse is that I cannot turn this feature off, not even by by changing
    ks->MAI->setRadix(16);
to
    ks->MAI->setRadix(10);
of ks_option in the llvm/keystone/ks.cpp file and recompiling.
I'm sure having the RADIX16 may be useful, but the user should hve the possibility to turn it on/off.

**Comment by JackieSpring** [comment]
[ OUT OF TOPIC ]
Talking about x86 GAS syntax, when I try to assemble this line:
    movl (%eax, %edx, 4), %esi
I get error 512 Invalid operand (KS_ERR_ASM_INVALIDOPERAND)
